# Generated by Django 4.2.2 on 2023-06-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('name_kaz', models.TextField(null=True)),
                ('name_rus', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='class_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('name_kaz', models.TextField(null=True)),
                ('name_rus', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='podclass_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('name_kaz', models.TextField(null=True)),
                ('name_rus', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spec_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('name_kaz', models.TextField(null=True)),
                ('name_rus', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classification_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('name_kaz', models.TextField(null=True)),
                ('name_rus', models.TextField(null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.category_income', verbose_name='Категория')),
                ('classs', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.class_income', verbose_name='Класс')),
                ('podclass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.podclass_income', verbose_name='Подкласс')),
                ('spec', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.spec_income', verbose_name='Специфика')),
            ],
        ),
    ]
