# Generated by Django 4.1.2 on 2023-06-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dirs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='budjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('name_kaz', models.TextField(null=True)),
                ('name_rus', models.TextField(null=True)),
                ('adress', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.TextField(null=True)),
                ('name_kaz', models.TextField(null=True)),
                ('name_rus', models.TextField(null=True)),
                ('adress', models.TextField(null=True)),
                ('_budjet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.budjet', verbose_name='Бюджет региона')),
            ],
        ),
    ]
