# Generated by Django 4.1.2 on 2023-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirs', '0004_type_izm_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
