# Generated by Django 4.1.2 on 2023-06-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dirs', '0006_abp_funcgroup_funcpodgroup_specexp_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fkr',
            name='_podprogram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.podprogram', verbose_name='Подпрограмма расхода'),
        ),
        migrations.AlterField(
            model_name='fkr',
            name='_program',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.program', verbose_name='Программа расхода'),
        ),
    ]
