# Generated by Django 4.1.2 on 2023-06-09 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dirs', '0003_rename_category_classification_income__category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='utv_inc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('_budjet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.budjet', verbose_name='Бюджет документа')),
                ('_organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.organization', verbose_name='Организация документа')),
            ],
        ),
        migrations.CreateModel(
            name='utv_inc_tbl1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.FloatField(null=True)),
                ('sm1', models.FloatField(null=True)),
                ('sm2', models.FloatField(null=True)),
                ('sm3', models.FloatField(null=True)),
                ('sm4', models.FloatField(null=True)),
                ('sm5', models.FloatField(null=True)),
                ('sm6', models.FloatField(null=True)),
                ('sm7', models.FloatField(null=True)),
                ('sm8', models.FloatField(null=True)),
                ('sm9', models.FloatField(null=True)),
                ('sm10', models.FloatField(null=True)),
                ('sm11', models.FloatField(null=True)),
                ('sm12', models.FloatField(null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('_classification', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.classification_income', verbose_name='Бюджет документа')),
                ('_utv_inc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='docs.utv_inc', verbose_name='ИД документа')),
            ],
        ),
    ]
