# Generated by Django 4.1.2 on 2023-06-12 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dirs', '0003_rename_category_classification_income__category_and_more'),
        ('docs', '0002_utv_inc_tbl1__organization_utv_inc_tbl1_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='izm_inc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('_budjet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.budjet', verbose_name='Бюджет документа')),
                ('_organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.organization', verbose_name='Организация документа')),
            ],
        ),
        migrations.AlterField(
            model_name='utv_inc_tbl1',
            name='_classification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.classification_income', verbose_name='Классификация документа'),
        ),
        migrations.CreateModel(
            name='izm_inc_tbl1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('god', models.FloatField(null=True)),
                ('sm1', models.FloatField(null=True)),
                ('sm2', models.FloatField(null=True)),
                ('sm3', models.FloatField(null=True)),
                ('sm4', models.FloatField(null=True)),
                ('sm5', models.FloatField(null=True)),
                ('sm6', models.FloatField(null=True)),
                ('sm7', models.FloatField(null=True)),
                ('sm8', models.FloatField(null=True)),
                ('sm9', models.FloatField(null=True)),
                ('sm10', models.FloatField(null=True)),
                ('sm11', models.FloatField(null=True)),
                ('sm12', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('_classification', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.classification_income', verbose_name='Классификация документа')),
                ('_izm_inc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='docs.izm_inc', verbose_name='ИД документа')),
                ('_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.organization', verbose_name='Организация документа')),
            ],
        ),
    ]
