# Generated by Django 4.1.2 on 2023-06-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_izm_inc_alter_utv_inc_tbl1__classification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izm_inc',
            old_name='date',
            new_name='_date',
        ),
        migrations.RenameField(
            model_name='izm_inc_tbl1',
            old_name='date',
            new_name='_date',
        ),
    ]
