# Generated by Django 4.1.2 on 2023-06-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_rename_date_izm_inc__date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utv_inc',
            old_name='date',
            new_name='_date',
        ),
        migrations.RenameField(
            model_name='utv_inc_tbl1',
            old_name='date',
            new_name='_date',
        ),
    ]
