# Generated by Django 4.1.2 on 2023-06-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dirs', '0004_type_izm_doc'),
        ('docs', '0005_rename_date_utv_inc__date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='izm_inc',
            name='_type_izm_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dirs.type_izm_doc', verbose_name='Тип справки'),
        ),
    ]
